export const Devs = [
{
    id: 1,
    nombre: "Ignacio",
    apellido: "Apaza",
    github: "https://github.com/ApazaIgnacio",
    Institucion: "Escuela de Minas",
    correo: "example@gmail.com",
    img: "https://avatars.githubusercontent.com/u/123456789?v=4",
  },
  {
    id: 2,
    nombre: "Ignacio",
    apellido: "Huanca",
    github: "https://github.com/Ignacio367",
    Institucion: "Escuela de Minas",
    correo: "example@gmail.com",
    img: "https://avatars.githubusercontent.com/u/123456789?v=4",
  },
  {
    id: 3,
    nombre: "Lucas",
    apellido: "Figueroa",
    github: "https://github.com/mikluha12",
    Institucion: "Escuela de Minas",
    correo: "example@gmail.com",
    img: "https://avatars.githubusercontent.com/u/123456789?v=4",
  },
  {
    id: 4,
    nombre: "Enrique",
    apellido: "Real",
    github: "https://github.com/Mageofdark",
    Institucion: "Escuela de Minas",
    correo: "example@gmail.com",
    img: "https://avatars.githubusercontent.com/u/123456789?v=4",
  },
  {
    id: 5,
    nombre: "Matias",
    apellido: "Velazquez",
    github: "https://github.com/matias12131",
    Institucion: "Escuela de Minas",
    correo: "example@gmail.com",
    img: "https://avatars.githubusercontent.com/u/123456789?v=4",
  },
  
]