export const Listado_productos = [
    {
        id: 1,
        imagen: "https://tiendanewsan.com.ar/media/catalog/product/n/1/n14p4020_7.jpg?auto=webp&format=pjpg&width=640&height=800&fit=cover",
        nombre: "Notebook Hp Amd Ryzen 5 7520u, 8gb Ram DDR5, 512gb Ssd, Pantalla 15.6 Full HD",
        precio: 876999,
        descripcion: "Ofrece un excelente rendimiento a un precio competitivo. Cuenta con un diseño elegante y portátil, perfecto para llevarla a cualquier lugar. Viene con Windows 11 Home, el sistema operativo más reciente de Microsoft. ¡No esperes más para disfrutar de la potencia y el rendimiento de la HP 15-FC0041WM! Adquirila ahora y llevá tu productividad al siguiente nivel.",
        categoria: "Tecnologia",
        stock: 10,
        visible: true,
    },
    {
        id: 2,
        imagen: "https://tiendanewsan.com.ar/media/catalog/product/9/1/91pb1j0042ar_nm.png?auto=webp&format=png&width=640&height=800&fit=cover",
        nombre: "Motorola Moto G32 128 GB Gris 6 GB RAM",
        precio: 259999,
        descripcion: "Con su potente procesador, tanto si juegas, reproduces en streaming o tomas fotos, el teléfono funciona a una temperatura más baja y con su memoria RAM de 6 GB tu equipo alcanzará un alto rendimiento con gran velocidad de transmisión de contenidos y ejecutará múltiples aplicaciones a la vez sin demoras.",
        categoria: "Tecnologia",
        stock: 10,
        visible: true,
    },
    {
        id: 3,
        imagen: "https://http2.mlstatic.com/D_NQ_NP_769567-MLA85934787465_062025-O.webp",
        nombre: "Guitarra Criolla Clasica Calidad Superior Funda Pua Manual Color Rojo ll ",
        precio: 78199,
        descripcion: "Gadnic lanza su línea de guitarras criollas con una hermosa terminación, cuerdas de bronce y nylon, ideales para completar tu interpretación musical. Este kit es perfecto para quienes inician en la música, con una construcción artesanal en madera, cuerdas de acero y un acabado brillante. Incluye una funda de nylon para su transporte y una púa.",
        categoria: "Musica",
        stock: 10,
        visible: true,
    },
]